
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Scale, OptionMenu, StringVar, HORIZONTAL


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("810x510")
window.configure(bg = "#CA8DE7")


canvas = Canvas(
    window,
    bg = "#CA8DE7",
    height = 510,
    width = 810,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=75.0,
    y=395.0,
    width=300.0,
    height=68.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=385.0,
    y=395.0,
    width=64.0,
    height=68.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=462.0,
    y=395.0,
    width=301.0,
    height=68.0
)

canvas.create_text(
    18.0,
    338.0,
    anchor="nw",
    text="audio:",
    fill="#FFFFFF",
    font=("Bauhaus 93", 18 * -1)
)

canvas.create_text(
    18.0,
    93.0,
    anchor="nw",
    text="\ntext:",
    fill="#FFFFFF",
    font=("Bauhaus 93", 18 * -1)
)

canvas.create_rectangle(
    0.0,
    0.0,
    810.0,
    104.0,
    fill="#4A514D",
    outline="")

canvas.create_text(
    215.0,
    16.0,
    anchor="nw",
    text="Text to Speech",
    fill="#FFFFFF",
    font=("Bauhaus 93", 64 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    421.5,
    222.5,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#F1F1F1",
    highlightthickness=0
)
entry_1.place(
    x=106.0,
    y=119.0,
    width=631.0,
    height=205.0
)

#combo box

choices = ['Voice male 1', 'Voice mail 2', 'Voice female 1', 'Voice female 2']
clicked = StringVar()
clicked.set(choices[0])

drop = OptionMenu(
    window,  
    clicked, 
    *choices
)
drop.place(
    x=80.0,
    y=345.0,
    width=295.0,
    height=60.0
)
speed = Scale(
    window, 
    from_=0.8, 
    to=1.2,
    resolution = 0.1, 
    orient=HORIZONTAL, 
    label = '                                          Speed'
)
speed.set(1)
speed.place(
    x=467.0,
    y=345.0,
    width=296.0,
)

window.resizable(False, False)
window.mainloop()
