
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer



# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, Scale, OptionMenu, StringVar, HORIZONTAL, Toplevel, Label
import requests
import json 
import os.path
import os
import pygame

pygame.mixer.init()

URL = ""

def GetText():
    data = entry_1.get("1.0","end-1c")
    return data

def GetVoiceType():
    choice_id = {
        "South women":"1",
        "Northern women": "2",
        "South men": "3",
        "Northern men": "4"
        }
    return choice_id[clicked.get()]

def GetVoiceSpeed():
    return str(speed.get())

def GetVoiceURL():
    if os.path.isfile("audio.wav"):
        pygame.mixer.music.unload()
        os.remove('audio.wav')
    headers = {
        'content-type': 'application/json',
    }
    data = {
        "text": GetText(),
        "voice_type": GetVoiceType(),
        "voice_speed": GetVoiceSpeed(),
        }
    json_object = json.dumps(data) 

    response = requests.post('https://middlemanapi.binh120702.repl.co/addrequest/', headers=headers, data=json_object)

    global URL
    URL = response.text
    return URL

playingAudio = True
def PlayAudio():
    global playingAudio
    if not os.path.isfile("audio.wav"):
        url = URL[1:-1]
        r = requests.get(url, allow_redirects=True)
        open('audio.wav', 'wb').write(r.content)

    if playingAudio and not pygame.mixer.music.get_busy():
        print(1)
        pygame.mixer.music.load("audio.wav")
        pygame.mixer.music.play(loops=0)
    elif playingAudio:
        print(2)
        pygame.mixer.music.pause()
        playingAudio = False
    else:
        print(3)
        pygame.mixer.music.unpause()
        playingAudio = True
def PopUpWindow():
    top = Toplevel(window)
    top.title("download")
    top.geometry("800x100")
    top.config(bg='green')
    l2 = Label(top, text = "Actually the audio is downloaded and saved as 'audio.wav' in the same directory :V. Just click 'Load the text' button to ensure")
    l2.pack(pady=40)

window = Tk()

window.iconbitmap('assets/tts.ico')
window.geometry("810x510")
window.configure(bg = "#CA8DE7")


canvas = Canvas(
    window,
    bg = "#CA8DE7",
    height = 510,
    width = 810,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file="assets/button_1.png")
button_1 = Button(
    activebackground = "#CA8DE7",
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=GetVoiceURL,
    relief="flat"
)
button_1.place(
    x=75.0,
    y=395.0,
    width=300.0,
    height=68.0
)

button_image_2 = PhotoImage(
    file="assets/button_2.png")
button_2 = Button(
    activebackground = "#CA8DE7",
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=PlayAudio,
    relief="flat"
)
button_2.place(
    x=385.0,
    y=395.0,
    width=64.0,
    height=68.0
)

button_image_3 = PhotoImage(
    file="assets/button_3.png")
button_3 = Button(
    activebackground = "#CA8DE7",
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=PopUpWindow,
    relief="flat"
)
button_3.place(
    x=462.0,
    y=395.0,
    width=301.0,
    height=68.0
)

canvas.create_text(
    18.0,
    338.0,
    anchor="nw",
    text="audio:",
    fill="#FFFFFF",
    font=("Bauhaus 93", 18 * -1)
)

canvas.create_text(
    18.0,
    93.0,
    anchor="nw",
    text="\ntext:",
    fill="#FFFFFF",
    font=("Bauhaus 93", 18 * -1)
)

canvas.create_rectangle(
    0.0,
    0.0,
    810.0,
    104.0,
    fill="#4A514D",
    outline="")

canvas.create_text(
    215.0,
    16.0,
    anchor="nw",
    text="Text to Speech",
    fill="#FFFFFF",
    font=("Bauhaus 93", 64 * -1)
)

entry_image_1 = PhotoImage(
    file="assets/entry_1.png")
entry_bg_1 = canvas.create_image(
    421.5,
    222.5,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#F1F1F1",
    highlightthickness=0
)
entry_1.place(
    x=106.0,
    y=119.0,
    width=631.0,
    height=205.0
)

#combo box
choices = ["South women","Northern women","South men","Northern men"]
clicked = StringVar()
clicked.set(choices[0])

drop = OptionMenu(
    window,  
    clicked, 
    *choices
)
drop.place(
    x=80.0,
    y=345.0,
    width=295.0,
    height=60.0
)
speed = Scale(
    window, 
    from_=0.8, 
    to=1.2,
    resolution = 0.1, 
    orient=HORIZONTAL, 
    label = '                                          Speed'
)
speed.set(1)
speed.place(
    x=467.0,
    y=345.0,
    width=296.0,
)

window.resizable(False, False)
window.mainloop()
